### PR TITLE
test: complete traverse, Parser, Parslet coverage

### PR DESCRIPTION
**Pull request by brettz9**
Just picking up else branch coverage where missing in a few files

- test: complete traverse, Parser, Parslet coverage
- test: complete Lexer coverage (failing string conditions, token, and `last`)
- test: complete tuple coverage (incomplete tuple, tuple with question mark)
- test: supply bad parser to trigger special types parslet error (otherwise shouldn't be triggered)

### CODE REVIEW

**Comment by simonseyock** [comment]
This is very nice, thank you! But I don't exactly see why we would need to have tests that specify behavior in case of undefined inputs? I am referring to the tests in `traverse`. Are you relying on that behavior?

**Comment by brettz9** [comment]
> This is very nice, thank you! But I don't exactly see why we would need to have tests that specify behavior in case of undefined inputs? I am referring to the tests in `traverse`. Are you relying on that behavior?

No, that was just to get else-branch coverage (toward 100% which can then be enforced in PRs). If it only goes within an `if` condition, and never skips over it (like if `onEnter` is always present for example), then this coverage will be missing (indicated in yellow rather than red).

**Comment by simonseyock** [comment]
Sorry for the late answer. I like the goal of having 100% coverage. But some of these tests seem a little awkward. I think they point to unnecessary if branches. Can I push to this branch? Then I will remove some if statements :)

**Comment by brettz9** [comment]
Sure, definitely. Feel free to change my PRs as you see fit, no less given that I'm just trying to get some low-hanging fruit expedited, hopefully in a way that expedites or at least points to things that could be done.

Nice thing with coverage is indeed helping find such unneeded code, so if not needed, by all means, please feel free to go ahead and remove.

**Review by simonseyock — APPROVED** [review]

**Comment by brettz9** [comment]
Thanks for the merge... Just a heads up... Getting this after running `npm i` (which I generally do on an update to make sure I have the latest version). Not sure if your routine can remove those fields before committing (unless I just have a different npm version)... Maybe see what happens for you upon `npm i`?

image

**Comment by simonseyock** [comment]
Thanks for the info. I tried it on my windows machine with node 16.13.1 and npm 7.24.2 and I do not get a diff after `npm i`. I try on my linux machine next week to see if I get different results.

**Pull request merged**
